apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: vector
  namespace: vector
spec:
  interval: 1h
  url: oci://ghcr.io/vectordotdev/helm-charts/vector
  ref:
    tag: 0.52.0
